# Plugins
plugins:
- jekyll-paginate
#- jekyll-gist
#- jekyll-feed

# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Chris Hodgson
tagline:          'A Jekyll theme'
description:      'Symfony, Laravel & ReactJs Developer'
url:              http://chrishodgsonweb.co.uk/
baseurl:          /

#author:
#  name:           'Mark Otto'
#  url:            https://twitter.com/mdo

paginate:         5
paginate_path: "/notes/page:num"

# Custom vars
#version:          2.1.0
google_analytics: UA-12262661-1
env: local

github:
  repo:           https://github.com/poole/hyde


# see http://jch.penibelst.de
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
  endings: all
  startings: [html, head, body]
  profile: false
  blanklines: false
  ignore:
    envs: [local]

defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      excerpt_separator: <!--more-->